// packages/ui/src/container/src/Container.vue
<template>
  <div
    v-if="display()"
    :id="`${config.id || ''}`"
    :class="`magic-ui-container${config.className ? ` ${config.className}` : ''}`"
    :style="style"
  >
    <slot></slot>
    <magic-ui-component
      v-for="item in config.items"
      :key="item.id"
      :config="item"
    ></magic-ui-component>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, PropType } from 'vue';

import type { MContainer } from '@tmagic/schema';

import Component from '../../Component.vue';
import useApp from '../../useApp';
import useCommonMethod from '../../useCommonMethod';

export default defineComponent({
  name: 'MagicUiContainer',

  components: {
    'magic-ui-component': Component,
  },

  props: {
    config: {
      type: Object as PropType<MContainer>,
      default: () => ({}),
    },
  },

  setup(props) {
    const app = useApp(props);

    return {
      style: computed(() => app?.transformStyle(props.config.style || {})),

      display: () => {
        const displayCfg = props.config?.display;

        if (typeof displayCfg === 'function') {
          return displayCfg(app);
        }
        return displayCfg !== false;
      },
      ...useCommonMethod(props),
    };
  },
});
</script>

// packages/ui-react/src/container/Container.tsx
import React from 'react';

import type { MComponent, MContainer } from '@tmagic/schema';

import useApp from '../useApp';

interface ContainerProps {
  config: MContainer;
  className: string;
  style: Record<string, any>;
  id: string;
}

const Container: React.FC<ContainerProps> = ({ config, id }) => {
  const { app } = useApp({ config });

  if (!app) return null;

  return (
    <div
      id={`${id || config.id || ''}`}
      className={`magic-ui-container${config.className ? ` ${config.className}` : ''}`}
      style={app.transformStyle(config.style || {})}
    >
      {config.items?.map((item: MComponent | MContainer) => {
        const MagicUiComp = app.resolveComponent(item.type || 'container');

        if (!MagicUiComp) return null;

        return (
          <MagicUiComp
            id={`${item.id || ''}`}
            key={item.id}
            config={item}
            className={`magic-ui-component${config.className ? ` ${config.className}` : ''}`}
            style={app.transformStyle(item.style || {})}
          ></MagicUiComp>
        );
      })}
    </div>
  );
};

Container.displayName = 'magic-ui-container';

export default Container;
