// packages/ui-vue2/src/page/Page.vue
<template>
  <div
    :id="config.id"
    :class="`magic-ui-page magic-ui-container${config.className ? ` ${config.className}` : ''}`"
    :style="style"
  >
    <slot></slot>
    <magic-ui-component
      v-for="item in config.items"
      :key="item.id"
      :config="item"
    ></magic-ui-component>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, PropType } from 'vue';

import type { MPage } from '@tmagic/schema';

import Component from '../Component.vue';
import useApp from '../useApp';

export default defineComponent({
  name: 'MagicUiPage',

  components: {
    'magic-ui-component': Component,
  },

  props: {
    config: {
      type: Object as PropType<MPage>,
      default: () => ({}),
    },
  },

  setup(props) {
    const app = useApp(props);

    return {
      style: computed(() => app?.transformStyle(props.config.style || {})),

      refresh() {
        window.location.reload();
      },
    };
  },
});
</script>

// ui/react/src/page/Page.tsx
import React from 'react';

import type { MComponent, MContainer, MPage } from '@tmagic/schema';

import useApp from '../useApp';

interface PageProps {
  config: MPage;
}

const Page: React.FC<PageProps> = ({ config }) => {
  const { app } = useApp({
    config,
    methods: {
      refresh: () => window.location.reload(),
    },
  });

  if (!app) return null;

  return (
    <div
      id={`${config.id || ''}`}
      className={`magic-ui-page magic-ui-container${
        config.className ? ` ${config.className}` : ''
      }`}
      style={app.transformStyle(config.style || {})}
    >
      {config.items?.map((item: MComponent | MContainer) => {
        const MagicUiComp = app.resolveComponent(item.type || 'container');

        if (!MagicUiComp) return null;

        return (
          <MagicUiComp
            id={`${item.id || ''}`}
            key={item.id}
            config={item}
            className={`magic-ui-component${config.className ? ` ${config.className}` : ''}`}
            style={app.transformStyle(item.style || {})}
          ></MagicUiComp>
        );
      })}
    </div>
  );
};

Page.displayName = 'magic-ui-page';

export default Page;
