// runtime/react/page/App.tsx
import React, { useContext } from 'react';

import Core from '@tmagic/core';
import type { Page } from '@tmagic/schema';
import { AppContent } from '@tmagic/ui-react';

function App() {
  const app = useContext<Core | undefined>(AppContent);

  if (!app?.page?.data) {
    return null;
  }

  const MagicUiPage = app.resolveComponent('page');

  return <MagicUiPage config={app?.page?.data as Page}></MagicUiPage>;
}

export default App;

// runtime/vue2/page/App.vue
<template>
  <magic-ui-page :config="pageConfig" />
</template>

<script lang="ts">
import { defineComponent, inject, reactive } from 'vue';

import Core from '@tmagic/core';

export default defineComponent({
  name: 'App',

  setup() {
    const app = inject<Core | undefined>('app');
    const pageConfig = reactive(app?.page?.data || {});

    return {
      pageConfig,
    };
  },
});
</script>
